workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: ساخت APK اندروید
        script: |
          find . -name "gradlew" -exec chmod +x {} \;
          find . -name "gradlew" -exec {} assembleDebug \;
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
