workflows:
  android-build:
    name: Tajrobehha Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - OPENROUTER

    scripts:
      - name: Prepare Gradle
        script: |
          gradle wrapper --gradle-version 8.9
          chmod +x gradlew

      - name: Get SHA1 and SHA-256
        script: |
          ./gradlew signingReport

      - name: Build Android APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
