plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.tajro.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tajro.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false

            buildConfigField "String",
                    "OPENROUTER_API_KEY",
                    "\"${System.getenv("OPENROUTER_API_KEY") ?: ""}\""
        }

        debug {
            buildConfigField "String",
                    "OPENROUTER_API_KEY",
                    "\"${System.getenv("OPENROUTER_API_KEY") ?: ""}\""
        }
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.18.0')

    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-ai'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-appcheck-debug'

    // Firebase Cloud Messaging
    implementation 'com.google.firebase:firebase-messaging'

    implementation 'com.google.guava:guava:31.0.1-android'

    // Unity Ads
    implementation 'com.unity3d.ads:unity-ads:4.20.0'
}
